### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by JOMOGO** [farshiana/checkers#1]
when executing the first command "npm install --production" I get this error.
I see you have included sudo in the command does this also work on windows if yes do I need to install something?

```npm ERR! code 1
npm ERR! path C:\Code\checkersTest\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Code\checkersTest\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Code\\checkersTest\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.17.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Code\checkersTest\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Code\checkersTest\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Code\checkersTest\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Code\checkersTest\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Code\checkersTest\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Code\checkersTest\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Code\checkersTest\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Code\checkersTest\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Code\checkersTest\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Code\checkersTest\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Code\checkersTest\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Code\checkersTest\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:206:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\Robin Groot\AppData\Local\Programs\Python\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\Robin Groot\AppData\Local\Programs\Python\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:400:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Code\\checkersTest\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Code\checkersTest\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Robin Groot\AppData\Local\npm-cache\_logs\2022-11-08T23_26_56_380Z-debug-0.log

```

**Comment by Cherebukha** [comment]
A wee bit late but try to downgrade your node version. Managed to install it with node v10.24.1.
